buku:
    path:     /
    defaults: { _controller: "CustomBukuBundle:Buku:index" }

buku_show:
    path:     /{id}/show
    defaults: { _controller: "CustomBukuBundle:Buku:show" }

buku_new:
    path:     /new
    defaults: { _controller: "CustomBukuBundle:Buku:new" }

buku_create:
    path:     /create
    defaults: { _controller: "CustomBukuBundle:Buku:create" }
    methods:  POST

buku_edit:
    path:     /{id}/edit
    defaults: { _controller: "CustomBukuBundle:Buku:edit" }

buku_update:
    path:     /{id}/update
    defaults: { _controller: "CustomBukuBundle:Buku:update" }
    methods:  [POST, PUT]

buku_delete:
    path:     /{id}/delete
    defaults: { _controller: "CustomBukuBundle:Buku:delete" }
    methods:  [POST, DELETE]
