<?php

namespace Custom\BukuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BukuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BukuRepository extends EntityRepository
{
}
